import type { ConfigPlugin } from '@expo/config-plugins';
import {
  AndroidConfig,
  withDangerousMod,
  withGradleProperties,
  withProjectBuildGradle,
  withSettingsGradle,
  withStringsXml,
} from '@expo/config-plugins';
import * as fs from 'fs';
import * as path from 'path';

const withUnity: ConfigPlugin<{ name?: string }> = (config, {} = {}) => {
  config = withProjectBuildGradleMod(config);
  config = withSettingsGradleMod(config);
  config = withGradlePropertiesMod(config);
  config = withStringsXMLMod(config);
  config = withIosFabricRegistration(config);
  return config;
};

const REPOSITORIES_END_LINE = `maven { url 'https://www.jitpack.io' }`;

const withProjectBuildGradleMod: ConfigPlugin = (config) =>
  withProjectBuildGradle(config, (modConfig) => {
    if (modConfig.modResults.contents.includes(REPOSITORIES_END_LINE)) {
      // use the last known line in expo's build.gradle file to append the newline after
      modConfig.modResults.contents = modConfig.modResults.contents.replace(
        REPOSITORIES_END_LINE,
        REPOSITORIES_END_LINE +
          '\nflatDir { dirs "${project(\':unityLibrary\').projectDir}/libs" }\n'
      );
    } else {
      throw new Error(
        'Failed to find the end of repositories in the android/build.gradle file`'
      );
    }
    return modConfig;
  });

const withSettingsGradleMod: ConfigPlugin = (config) =>
  withSettingsGradle(config, (modConfig) => {
    if (!modConfig.modResults.contents.includes(':unityLibrary')) {
      modConfig.modResults.contents += `
include ':unityLibrary'
project(':unityLibrary').projectDir=new File('../unity/builds/android/unityLibrary')
    `;
    }
    return modConfig;
  });

const withGradlePropertiesMod: ConfigPlugin = (config) =>
  withGradleProperties(config, (modConfig) => {
    const alreadySet = modConfig.modResults.some(
      (item) => item.type === 'property' && item.key === 'unityStreamingAssets'
    );
    if (!alreadySet) {
      modConfig.modResults.push({
        type: 'property',
        key: 'unityStreamingAssets',
        value: '.unity3d',
      });
    }
    return modConfig;
  });

// add string
const withStringsXMLMod: ConfigPlugin = (config) =>
  withStringsXml(config, (modConfig) => {
    modConfig.modResults = AndroidConfig.Strings.setStringItem(
      [
        {
          _: 'Game View',
          $: {
            name: 'game_view_content_description',
          },
        },
      ],
      modConfig.modResults
    );
    return modConfig;
  });

// Patches RCTThirdPartyComponentsProvider.mm (generated by expo prebuild) to register
// RNUnityView with Fabric's component registry so that updateProps is dispatched correctly.
const withIosFabricRegistration: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    'ios',
    (modConfig) => {
      const iosRoot = modConfig.modRequest.platformProjectRoot;
      const projectName = modConfig.modRequest.projectName ?? '';

      // The file may be at the ios/ root or inside ios/<AppName>/
      const candidates = [
        path.join(iosRoot, 'RCTThirdPartyComponentsProvider.mm'),
        path.join(iosRoot, projectName, 'RCTThirdPartyComponentsProvider.mm'),
      ];

      const providerPath = candidates.find((p) => fs.existsSync(p));
      if (!providerPath) {
        console.warn(
          '[react-native-unity] RCTThirdPartyComponentsProvider.mm not found. ' +
            'RNUnityView may not be registered with Fabric. ' +
            'Run `npx expo prebuild` again after the initial build.'
        );
        return modConfig;
      }

      let contents = fs.readFileSync(providerPath, 'utf-8');

      const dictEntry = `@"RNUnityView" : RNUnityViewCls(),`;

      // Nothing to do if already patched
      if (contents.includes(dictEntry)) {
        return modConfig;
      }

      const forwardDecl =
        'Class<RCTComponentViewProtocol> RNUnityViewCls(void);';

      // Insert forward declaration before @implementation
      if (!contents.includes(forwardDecl)) {
        contents = contents.replace(
          /(@implementation RCTThirdPartyComponentsProvider)/,
          `${forwardDecl}\n\n$1`
        );
      }

      // Insert dictionary entry before the closing }; of the components dict.
      // The dict sits inside a dispatch_once block so the unique pattern is:
      //   (indent)};(whitespace)});
      contents = contents.replace(
        /([ \t]*)(};)([ \t]*\n[ \t]*\}\);)/,
        `$1  ${dictEntry}\n$1$2$3`
      );

      fs.writeFileSync(providerPath, contents, 'utf-8');

      return modConfig;
    },
  ]);

export default withUnity;
